const assert = require('node:assert/strict');
const fs = require('node:fs');

const checkLayout = async page => {
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'No horizontal overflow');
};
const screenshot = async (page,path) => {
  await page.evaluate(() => window.scrollTo(0,0));
  await page.screenshot({path,fullPage:true});
};
const chooseEnglish = page => page.getByRole('combobox', {name:'لغة الواجهة',exact:true}).selectOption('en');
const chooseArabic = page => page.getByRole('combobox', {name:'Interface language',exact:true}).selectOption('ar');

module.exports = async function arabicTests(browser, demo, cloud) {
  const context = await browser.newContext({locale:'ar-AE',timezoneId:'Asia/Dubai',viewport:{width:360,height:800}});
  const page = await context.newPage();
  const errors = [], blocked = [];
  page.on('pageerror', error => errors.push(error.message));
  await context.route('**/*', route => {
    if (new URL(route.request().url()).origin === demo) return route.continue();
    blocked.push(route.request().url());
    return route.fulfill({status:403,body:'Blocked by isolated test'});
  });
  fs.mkdirSync('/tmp/aasiflow-qa',{recursive:true});
  try {
    await page.goto(demo);
    await page.getByRole('heading',{name:'مساحة المحتوى الخاصة بك'}).waitFor();
    assert.deepEqual(await page.evaluate(() => [document.documentElement.lang,document.documentElement.dir]), ['ar','rtl']);
    await checkLayout(page);
    await screenshot(page,'/tmp/aasiflow-qa/arabic-mobile-dashboard.png');
    await page.setViewportSize({width:1440,height:1000});
    const aside = await page.locator('.sidebar').boundingBox();
    const main = await page.locator('.app-shell main').boundingBox();
    assert.equal(aside.x + aside.width,1440);
    assert(main.x + main.width <= aside.x, 'Desktop RTL sidebar is on the right without covering content');
    await checkLayout(page);
    await screenshot(page,'/tmp/aasiflow-qa/arabic-desktop-dashboard.png');
    await page.setViewportSize({width:360,height:800});
    await page.getByRole('button',{name:'منشور جديد',exact:true}).click();
    assert.equal(await page.getByLabel('لغة المحتوى',{exact:true}).inputValue(), 'Arabic');
    const idea = 'خمس أفكار لتحسين محتوى المشاريع الصغيرة في دبي <img src=x onerror=alert(1)>';
    const caption = 'محتوى عربي يوضح أفكارًا عملية في دبي — Dubai 2026';
    await page.getByLabel('فكرة المحتوى',{exact:true}).fill(idea);
    await page.getByLabel('أسلوب الكتابة',{exact:true}).selectOption('Professional');
    await page.getByRole('button',{name:'استخدام قالب محلي'}).click();
    await page.getByLabel('نص المنشور',{exact:true}).fill(caption);
    await page.getByLabel('الوسوم',{exact:true}).fill('#دبي #محتوى #Dubai');
    await page.getByLabel('راجعت هذا المحتوى وأوافق عليه',{exact:true}).check();
    await chooseEnglish(page);
    assert.equal(await page.getByLabel('Content idea',{exact:true}).inputValue(),idea);
    assert.equal(await page.getByLabel('Caption',{exact:true}).inputValue(),caption);
    assert.equal(await page.getByLabel('Tone',{exact:true}).inputValue(),'Professional');
    assert.equal(await page.getByLabel('Language',{exact:true}).inputValue(),'Arabic');
    assert.equal(await page.getByLabel('I reviewed and approve this content',{exact:true}).isChecked(),true);
    await chooseArabic(page);
    assert.equal(await page.getByLabel('راجعت هذا المحتوى وأوافق عليه',{exact:true}).isChecked(),true);
    await checkLayout(page);
    await screenshot(page,'/tmp/aasiflow-qa/arabic-mobile-editor.png');
    await page.getByRole('button',{name:'حفظ المسودة',exact:true}).click();
    await page.getByText('تم حفظ المسودة.',{exact:true}).waitFor();
    await page.reload();
    assert.equal(await page.getByRole('combobox',{name:'لغة الواجهة',exact:true}).inputValue(),'ar');
    const title = page.locator('.post strong');
    await title.waitFor();
    assert.equal(await title.textContent(),idea);
    assert.equal(await title.getAttribute('dir'),'auto');
    assert.equal(await page.locator('.post img').count(),0, 'User markup is rendered as literal text');
    await page.getByRole('button',{name:'متابعة المسودة'}).click();
    assert.equal(await page.getByLabel('نص المنشور',{exact:true}).inputValue(),caption);
    await page.getByLabel('راجعت هذا المحتوى وأوافق عليه',{exact:true}).check();
    await page.getByRole('button',{name:'اعتماد وحفظ',exact:true}).click();
    await page.getByRole('button',{name:'فتح القائمة',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('.sidebar').getBoundingClientRect().right <= innerWidth);
    const drawer = await page.locator('.sidebar').boundingBox();
    assert.equal(drawer.x + drawer.width,360);
    await page.getByRole('button',{name:'تقويم المحتوى',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('.sidebar').getBoundingClientRect().left >= innerWidth);
    const time = page.getByLabel(`تحديد موعد ${idea}`,{exact:true});
    assert.equal(await time.getAttribute('dir'),'ltr');
    await time.fill('2020-01-01T10:00');
    await page.getByRole('button',{name:'تحديد موعد',exact:true}).click();
    await page.getByText('اختر تاريخًا ووقتًا في المستقبل.',{exact:true}).waitFor();
    await time.fill('2099-01-01T10:00');
    await chooseEnglish(page);
    assert.equal(await page.getByLabel(`Schedule ${idea}`,{exact:true}).inputValue(),'2099-01-01T10:00');
    await chooseArabic(page);
    await page.getByRole('button',{name:'تحديد موعد',exact:true}).click();
    await page.getByRole('button',{name:'إلغاء الموعد',exact:true}).waitFor();
    let posts = await page.evaluate(() => JSON.parse(localStorage.getItem('aasiflow-posts')));
    assert.equal(posts[0].scheduledFor,'2099-01-01T06:00:00.000Z','Dubai input is stored as UTC, not shifted by UI language');
    assert.equal(posts[0].tone,'Professional');
    assert.equal(posts[0].language,'Arabic');
    assert.deepEqual(posts[0].hashtags,['دبي','محتوى','Dubai']);
    await page.getByText(/Asia\/Dubai/).waitFor();
    await checkLayout(page);
    await screenshot(page,'/tmp/aasiflow-qa/arabic-mobile-calendar.png');
    await page.getByRole('button',{name:'عرض',exact:true}).click();
    await page.getByRole('button',{name:'تعديل',exact:true}).click();
    assert.equal(await page.getByLabel('راجعت هذا المحتوى وأوافق عليه',{exact:true}).isChecked(),false);
    posts = await page.evaluate(() => JSON.parse(localStorage.getItem('aasiflow-posts')));
    assert.equal(posts[0].status,'draft');
    assert.equal(posts[0].scheduledFor,undefined);
    await chooseEnglish(page);
    await page.getByLabel('Language',{exact:true}).selectOption('English');
    await page.getByRole('button',{name:'Update draft',exact:true}).click();
    await page.getByText('Draft saved.',{exact:true}).waitFor();
    await chooseArabic(page);
    await page.reload();
    await page.getByRole('button',{name:'متابعة المسودة'}).click();
    assert.equal(await page.getByLabel('لغة المحتوى',{exact:true}).inputValue(),'English','Arabic interface preserves an existing English draft language');
    await page.getByRole('button',{name:'فتح القائمة',exact:true}).click();
    await page.getByRole('button',{name:'الحسابات والإعدادات',exact:true}).click();
    await page.getByRole('heading',{name:'الحسابات وحالة التفعيل'}).waitFor();
    assert.equal(await page.getByRole('button',{name:'إضافة المنشور المعتمد إلى قائمة النشر'}).isDisabled(),true);
    assert.equal(await page.getByRole('button',{name:'ربط حساب',exact:true}).first().isDisabled(),true);
    assert.equal(await page.getByRole('button',{name:'المتابعة إلى صفحة الدفع الآمنة'}).count(),0);
    await checkLayout(page);
    await screenshot(page,'/tmp/aasiflow-qa/arabic-mobile-connections.png');
    await page.setViewportSize({width:1440,height:1000});
    await checkLayout(page);
    await screenshot(page,'/tmp/aasiflow-qa/arabic-desktop-connections.png');
    assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);
    console.log('PASS: Arabic RTL on 360/1440px, persistent language, literal Arabic content, canonical values, unsaved draft/approval preservation, Dubai calendar UTC and closed demo gates.');
  } finally { await context.close(); }
  if (cloud) await arabicCloudTest(browser,cloud);
};

async function arabicCloudTest(browser,base) {
  const context = await browser.newContext({locale:'ar-AE',timezoneId:'Asia/Dubai',viewport:{width:360,height:800}});
  const page = await context.newPage();
  const errors = [], blocked = [], requests = []; let rows = [];
  const id = 'b1111111-1111-4111-8111-111111111111';
  const user = {id,aud:'authenticated',role:'authenticated',email:'arabic-fixture@example.invalid',app_metadata:{provider:'email'},user_metadata:{},identities:[],created_at:new Date().toISOString()};
  const encode = value => Buffer.from(JSON.stringify(value)).toString('base64url');
  const token = `${encode({alg:'HS256',typ:'JWT'})}.${encode({sub:id,session_id:'b3333333-3333-4333-8333-333333333333',role:'authenticated',exp:Math.floor(Date.now()/1000)+3600})}.test-signature`;
  page.on('pageerror',error => errors.push(error.message));
  await context.route('**/*',async route => {
    const req = route.request(), url = new URL(req.url());
    if (url.origin === base) return route.continue();
    if (url.origin !== 'https://fixture.supabase.co') {blocked.push(url.toString());return route.fulfill({status:403,body:'Blocked by isolated test'});}
    const cors = {'Access-Control-Allow-Origin':base,'Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info,x-supabase-api-version'};
    if (req.method() === 'OPTIONS') return route.fulfill({status:204,headers:cors});
    let body; try {body = req.postDataJSON();} catch {}
    requests.push({path:url.pathname,method:req.method(),query:url.searchParams.toString(),body});
    const send = data => route.fulfill({json:data,headers:cors});
    if (url.pathname === '/auth/v1/token') return send({access_token:token,refresh_token:'arabic-fixture-token',token_type:'bearer',expires_in:3600,user});
    if (url.pathname === '/auth/v1/user') return send(user);
    if (url.pathname === '/auth/v1/signup') return send({user,session:null});
    if (['/auth/v1/recover','/auth/v1/resend','/auth/v1/logout'].includes(url.pathname)) return send({});
    if (url.pathname === '/rest/v1/posts') {
      if (['POST','PATCH'].includes(req.method())) {const row = {...body,revision:1};rows = [row];return send(row);}
      return send(rows);
    }
    if (url.pathname === '/rest/v1/rpc/launch_status') return send({publishing:false,billing:false});
    if (url.pathname === '/rest/v1/rpc/usage_summary') return send({attempts:2,credits:0});
    if (['/rest/v1/social_connections','/rest/v1/publication_jobs','/rest/v1/post_metrics'].includes(url.pathname)) return send([]);
    if (url.pathname === '/functions/v1/social-account') return send({instagram:false,linkedin:false,publishing:false});
    if (url.pathname === '/functions/v1/generate-content') return send({caption:'أفكار واضحة للمشاريع الصغيرة في دبي',hashtags:['دبي','أفكار']});
    blocked.push(url.toString());return route.fulfill({status:404,body:'Unexpected test request'});
  });
  try {
    await page.goto(base);
    await page.getByRole('button',{name:'ليس لديك حساب؟ أنشئ حسابًا'}).click();
    await page.getByLabel('البريد الإلكتروني',{exact:true}).fill(user.email);
    assert.equal(await page.getByLabel('البريد الإلكتروني',{exact:true}).getAttribute('dir'),'ltr');
    await page.getByLabel('كلمة المرور',{exact:true}).fill('short');
    await page.getByRole('button',{name:'إنشاء حساب',exact:true}).click();
    assert.equal(requests.some(req => req.path === '/auth/v1/signup'),false);
    await page.getByLabel('كلمة المرور',{exact:true}).fill('arabic fixture passphrase');
    await chooseEnglish(page);
    assert.equal(await page.getByLabel('Password',{exact:true}).inputValue(),'arabic fixture passphrase');
    await chooseArabic(page);
    await page.getByRole('button',{name:'إنشاء حساب',exact:true}).click();
    await page.getByText('افتح بريدك الإلكتروني لتأكيد الحساب، ثم سجّل الدخول.',{exact:true}).waitFor();
    const signup = requests.find(req => req.path === '/auth/v1/signup');
    assert.equal(signup.body.code_challenge_method,'s256');
    assert.equal(new URLSearchParams(signup.query).get('redirect_to'),`${base}/?flow=confirmed`);
    await page.reload();
    await page.getByRole('button',{name:'نسيت كلمة المرور؟'}).click();
    await page.getByLabel('البريد الإلكتروني',{exact:true}).fill(user.email);
    await page.getByRole('button',{name:'إرسال رابط إعادة التعيين',exact:true}).click();
    await page.getByText('إذا كان الحساب مؤهلًا لاستقبال الرسالة، فقد أُرسل الرابط. افتحه في هذا المتصفح وتحقق أيضًا من البريد غير المرغوب فيه.',{exact:true}).waitFor();
    await page.getByRole('button',{name:'إرسال رابط إعادة التعيين',exact:true}).click();
    await page.getByText('يرجى الانتظار دقيقة قبل طلب رسالة بريد أخرى.',{exact:true}).waitFor();
    assert.equal(requests.filter(req => req.path === '/auth/v1/recover').length,1);
    const recovery = requests.find(req => req.path === '/auth/v1/recover');
    assert.equal(recovery.body.code_challenge_method,'s256');
    assert.equal(new URLSearchParams(recovery.query).get('redirect_to'),`${base}/?flow=recovery`);
    await checkLayout(page);
    await screenshot(page,'/tmp/aasiflow-qa/arabic-mobile-password-reset.png');
    await page.reload();
    await page.getByRole('button',{name:'إعادة إرسال بريد التأكيد'}).click();
    await page.getByLabel('البريد الإلكتروني',{exact:true}).fill(user.email);
    await page.getByRole('button',{name:'إعادة إرسال رابط التأكيد',exact:true}).click();
    await page.getByText('إذا كان الحساب مؤهلًا لاستقبال الرسالة، فقد أُرسل الرابط. افتحه في هذا المتصفح وتحقق أيضًا من البريد غير المرغوب فيه.',{exact:true}).waitFor();
    assert.equal(new URLSearchParams(requests.find(req => req.path === '/auth/v1/resend').query).get('redirect_to'),`${base}/?flow=confirmed`);
    await page.reload();
    await page.getByLabel('البريد الإلكتروني',{exact:true}).fill(user.email);
    await page.getByLabel('كلمة المرور',{exact:true}).fill('arabic fixture passphrase');
    await page.getByRole('button',{name:'تسجيل الدخول',exact:true}).click();
    await page.getByRole('button',{name:'منشور جديد',exact:true}).click();
    await page.getByLabel('فكرة المحتوى',{exact:true}).fill('أفكار تسويقية عملية للمشاريع في دبي');
    await page.getByLabel('أسلوب الكتابة',{exact:true}).selectOption('Professional');
    await page.getByRole('button',{name:'إنشاء بالذكاء الاصطناعي',exact:true}).click();
    await page.getByLabel('نص المنشور',{exact:true}).waitFor();
    const generated = requests.find(req => req.path === '/functions/v1/generate-content');
    assert.equal(generated.body.language,'Arabic');assert.equal(generated.body.tone,'Professional');assert.equal(generated.body.platform,'Instagram');
    await page.getByRole('button',{name:'حفظ المسودة',exact:true}).click();
    await page.getByText('تم حفظ المسودة.',{exact:true}).waitFor();
    assert.equal(rows[0].language,'Arabic');assert.equal(rows[0].tone,'Professional');assert.equal(rows[0].status,'draft');
    assert.deepEqual(rows[0].hashtags,['دبي','أفكار']);
    await page.getByRole('button',{name:'فتح القائمة',exact:true}).click();
    await page.getByRole('button',{name:'الحسابات والإعدادات',exact:true}).click();
    await page.getByText('2 محاولات ذكاء اصطناعي اليوم بتوقيت UTC. الرصيد: 0.',{exact:true}).waitFor();
    assert.equal(await page.getByRole('button',{name:'إضافة المنشور المعتمد إلى قائمة النشر'}).isDisabled(),true);
    assert.equal(await page.getByRole('button',{name:'ربط حساب',exact:true}).first().isDisabled(),true);
    assert.equal(requests.some(req => req.path.includes('payment-checkout')),false);
    await page.evaluate(userId => sessionStorage.setItem(`aasiflow-recovery-${userId}`,String(Date.now()+600000)),id);
    await page.reload();
    await page.getByRole('heading',{name:'اختر كلمة مرور جديدة'}).waitFor();
    await page.getByLabel('كلمة المرور الجديدة',{exact:true}).fill('new arabic fixture passphrase');
    await page.getByLabel('تأكيد كلمة المرور الجديدة',{exact:true}).fill('different fixture passphrase');
    await page.getByRole('button',{name:'تحديث كلمة المرور',exact:true}).click();
    await page.getByText('كلمتا المرور غير متطابقتين.',{exact:true}).waitFor();
    assert.equal(requests.some(req => req.method === 'PUT'),false);
    await page.getByLabel('تأكيد كلمة المرور الجديدة',{exact:true}).fill('new arabic fixture passphrase');
    await chooseEnglish(page);
    assert.equal(await page.getByLabel('New password',{exact:true}).inputValue(),'new arabic fixture passphrase');
    await chooseArabic(page);
    await page.getByRole('button',{name:'تحديث كلمة المرور',exact:true}).click();
    await page.getByText('تم تحديث كلمة المرور. سجّل الدخول بكلمة المرور الجديدة.',{exact:true}).waitFor();
    assert(requests.some(req => req.path === '/auth/v1/logout' && new URLSearchParams(req.query).get('scope') === 'global'));
    assert.equal(await page.getByLabel('كلمة المرور',{exact:true}).inputValue(),'');
    await checkLayout(page);
    assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);
    console.log('PASS: Arabic mocked Auth minimum/PKCE/resend/cooldown/recovery/global logout, canonical AI/save payload and closed cloud gates. No actual provider calls or email.');
  } finally {await context.close();}
}
