const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});
 const page = await browser.newPage({viewport:{width:390,height:844}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173');
 await page.getByRole('button',{name:'New post',exact:true}).click();
 await page.getByLabel('Content idea').fill('Five ways to improve small business content');
 await page.getByRole('button',{name:'Use local template'}).click();
 await page.getByLabel('I reviewed and approve this content').check();
 await page.getByLabel('Caption',{exact:true}).fill('An edited caption');
 assert.equal(await page.getByLabel('I reviewed and approve this content').isChecked(),false);
 await page.getByRole('button',{name:'Save draft',exact:true}).click();
 await page.getByText('Draft saved.',{exact:true}).waitFor();
 await page.reload();
 await page.getByRole('button',{name:'Continue draft'}).click();
 assert.equal(await page.getByLabel('Caption',{exact:true}).inputValue(),'An edited caption');
 await page.getByLabel('I reviewed and approve this content').check();
 await page.getByRole('button',{name:'Approve & save'}).click();
 await page.getByRole('button',{name:'View',exact:true}).click();
 await page.getByRole('button',{name:'Edit',exact:true}).click();
 assert.equal(await page.getByLabel('I reviewed and approve this content').isChecked(),false);
 await page.getByLabel('I reviewed and approve this content').check();
 await page.getByRole('button',{name:'Approve & save'}).click();
 await page.getByRole('button',{name:'Open navigation'}).click();
 await page.getByRole('button',{name:'Content calendar',exact:true}).click();
 await page.getByLabel('Schedule Five ways to improve small business content').fill('2020-01-01T10:00');
 await page.getByRole('button',{name:'Schedule',exact:true}).click();
 await page.getByText('Choose a future date and time.',{exact:true}).waitFor();
 await page.getByLabel('Schedule Five ways to improve small business content').fill('2099-01-01T10:00');
 await page.getByRole('button',{name:'Schedule',exact:true}).click();
 await page.getByRole('button',{name:'Unschedule',exact:true}).waitFor();
 await page.getByRole('button',{name:'View',exact:true}).click();
 await page.getByRole('button',{name:'Edit',exact:true}).click();
 const posts=await page.evaluate(()=>JSON.parse(localStorage.getItem('aasiflow-posts')));
 assert.equal(posts[0].status,'draft');assert.equal(posts[0].scheduledFor,undefined);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: mobile draft persistence, approval reset, read-only edit, past-date rejection, scheduling and unscheduling on edit; no runtime errors.');
})().catch(e=>{console.error(e);process.exit(1)});
