import assert from 'node:assert/strict'
import { readFile, readdir } from 'node:fs/promises'
import { PGlite } from '@electric-sql/pglite'
const db = new PGlite()
let checks = 0
const equal = (actual,expected) => { assert.deepEqual(actual,expected); checks++ }
const value = async (sql,params=[]) => Object.values((await db.query(sql,params)).rows[0])[0]
const rejects = async (sql,params=[]) => { await assert.rejects(db.query(sql,params));checks++ }
const runAs = async (role,uid,sid) => {
  await db.exec('reset role')
  await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({role,...(uid?{sub:uid,session_id:sid}: {})})])
  await db.exec(`set role ${role}`)
}
const A='a1111111-1111-4111-8111-111111111111',B='b2222222-2222-4222-8222-222222222222'
const SA='a3333333-3333-4333-8333-333333333333',SB='b4444444-4444-4444-8444-444444444444'
const C='c5555555-5555-4555-8555-555555555555',P='d6666666-6666-4666-8666-666666666666',O='e7777777-7777-4777-8777-777777777777'
try {
  await db.exec(await readFile('tests/local-bootstrap.sql','utf8'))
  for (const filename of (await readdir('supabase/migrations')).filter(name=>/^\d+_.+\.sql$/.test(name)).sort()) await db.exec(await readFile(`supabase/migrations/${filename}`,'utf8'))
  const baseline = await db.exec(await readFile('tests/live-database.sql','utf8'))
  equal(String(baseline.at(-1).rows[0].verification).startsWith('PASS:'),true)
  const paymentBaseline = await db.exec(await readFile('tests/live-payment-database.sql','utf8'))
  equal(String(paymentBaseline.at(-1).rows[0].verification).startsWith('PASS:'),true)
  await db.query('insert into auth.users(id) values($1),($2)',[A,B])
  await db.query('insert into auth.sessions(id,user_id) values($1,$2),($3,$4)',[SA,A,SB,B])
  await runAs('authenticated',A,SA)
  equal(await value('select public.has_active_session()'),true)
  await db.query("insert into public.posts(id,user_id,idea,platform,tone,caption,status) values($1,$2,'Approval test','LinkedIn','Friendly','Reviewed caption','approved')",[P,A])
  equal(await value('select revision from public.posts where id=$1',[P]),1)
  await rejects("select public.enqueue_publication($1,$2,1,now())",[P,C])
  for (const name of ['social_connections','publication_jobs','post_metrics','payment_orders','credit_ledger']) await rejects(`insert into public.${name} default values`)
  await rejects('select public.service_claim_publication()')
  await rejects('select public.service_read_credential($1)',[C])
  await rejects('select * from private.social_credentials')
  await rejects("update public.posts set caption=repeat('x',3001) where id=$1",[P])
  await rejects("update public.posts set hashtags=array['bad tag'] where id=$1",[P])
  await runAs('postgres')
  await db.query("insert into public.social_connections(id,user_id,provider,account_id,account_name,expires_at) values($1,$2,'linkedin','member123','Test profile',now()+interval '30 days')",[C,A])
  await runAs('authenticated',B,SB)
  equal(await value('select count(*)::int from public.social_connections'),0)
  equal(await value('select count(*)::int from public.posts'),0)
  await runAs('postgres')
  equal(await value('select publishing_enabled from private.launch_controls'),false)
  equal(await value('select billing_enabled from private.launch_controls'),false)
  // Gates are changed only in this in-memory database. No network exists here.
  await db.exec('update private.launch_controls set publishing_enabled=true,billing_enabled=true')
  await runAs('authenticated',A,SA)
  await rejects('select public.enqueue_publication($1,$2,999,now())',[P,C])
  const J = await value('select public.enqueue_publication($1,$2,1,now())',[P,C])
  await rejects('select public.enqueue_publication($1,$2,1,now())',[P,C])
  await db.query("update public.posts set caption='Content changed' where id=$1",[P])
  equal(await value('select status from public.posts where id=$1',[P]),'draft')
  equal(await value('select status from public.publication_jobs where id=$1',[J]),'cancelled')
  equal(await value('select revision from public.posts where id=$1',[P]),2)
  const stale = await db.query("update public.posts set caption='Stale browser' where id=$1 and revision=1 returning id",[P]);equal(stale.rows.length,0)
  await db.query("update public.posts set status='approved' where id=$1",[P])
  const J2 = await value('select public.enqueue_publication($1,$2,3,now())',[P,C])
  await runAs('service_role')
  const claim = await value('select public.service_claim_publication()');equal(claim.id,J2)
  equal(await value('select public.service_claim_publication()'),null)
  await runAs('authenticated',A,SA)
  await rejects("update public.posts set caption='Edit in flight' where id=$1",[P])
  equal(await value('select public.cancel_publication($1)',[J2]),false)
  await runAs('service_role')
  equal(await value("select public.service_finish_publication($1,$2,'published','urn:li:share:123',null,null)",[J2,SA]),false)
  equal(await value("select public.service_finish_publication($1,$2,'uncertain',null,null,'timeout')",[J2,claim.lease_id]),true)
  await runAs('authenticated',A,SA)
  await db.query("update public.posts set caption='New reviewed words' where id=$1",[P])
  await db.query("update public.posts set status='approved' where id=$1",[P])
  await rejects('select public.enqueue_publication($1,$2,5,now())',[P,C])
  await runAs('service_role')
  equal(await value('select public.service_oauth_start($1,$2,$3,$4)',['a'.repeat(64),A,SA,'linkedin']),true)
  const state = await value('select public.service_oauth_take($1)',['a'.repeat(64)]);equal(state.user_id,A)
  equal(await value('select public.service_oauth_take($1)',['a'.repeat(64)]),null)
  equal(await value('select public.service_oauth_start($1,$2,$3,$4)',['b'.repeat(64),A,SA,'linkedin']),true)
  await runAs('postgres')
  await db.exec("update private.oauth_states set expires_at=now()-interval '1 second'")
  await runAs('service_role');equal(await value('select public.service_oauth_take($1)',['b'.repeat(64)]),null)
  await db.query("insert into public.payment_orders(id,user_id,plan_id,amount,credits,provider_link_id,status) values($1,$2,'test',10000,2,'plink_Test123','pending')",[O,A])
  equal(await value('select public.service_record_payment($1,$2,$3,$4,$5,$6)',['evt_wrong','plink_Test123',O,1,'INR','pay_Test123']),false)
  equal(await value('select public.service_record_payment($1,$2,$3,$4,$5,$6)',['evt_paid','plink_Test123',O,10000,'INR','pay_Test123']),true)
  equal(await value('select public.service_record_payment($1,$2,$3,$4,$5,$6)',['evt_paid','plink_Test123',O,10000,'INR','pay_Test123']),true)
  equal(await value('select public.service_record_payment($1,$2,$3,$4,$5,$6)',['evt_replay_new_id','plink_Test123',O,10000,'INR','pay_Test123']),true)
  equal(await value('select sum(credits)::int from public.credit_ledger'),2)
  await runAs('authenticated',A,SA)
  const attempts=[];for(let i=0;i<23;i++) attempts.push(await value('select public.consume_ai_quota()'))
  equal(attempts.filter(Boolean).length,22)
  equal(await value('select sum(credits)::int from public.credit_ledger'),0)
  equal(await value('select calls from public.ai_usage'),22)
  equal((await value('select public.usage_summary()')).credits,0)
  await runAs('service_role')
  equal(await value('select public.service_record_refund($1,$2,$3,$4,$5)',['evt_over','rfnd_Over123','pay_Test123',10001,'INR']),false)
  equal(await value('select public.service_record_refund($1,$2,$3,$4,$5)',['evt_refund1','rfnd_First123','pay_Test123',5000,'INR']),true)
  equal(await value('select public.service_record_refund($1,$2,$3,$4,$5)',['evt_refund1','rfnd_First123','pay_Test123',5000,'INR']),true)
  equal(await value('select sum(credits)::int from public.credit_ledger'),-1)
  equal(await value('select public.service_record_refund($1,$2,$3,$4,$5)',['evt_refund2','rfnd_Second123','pay_Test123',5000,'INR']),true)
  equal(await value('select status from public.payment_orders where id=$1',[O]),'refunded')
  equal(await value('select public.service_record_payment($1,$2,$3,$4,$5,$6)',['evt_paid_after_refund','plink_Test123',O,10000,'INR','pay_Test123']),true)
  equal(await value('select status from public.payment_orders where id=$1',[O]),'refunded')
  equal(await value('select sum(credits)::int from public.credit_ledger'),-2)
  await runAs('authenticated',A,SA)
  equal(await value('select public.consume_ai_quota()'),false)
  equal((await value('select public.usage_summary()')).credits,-2)
  await runAs('authenticated',B,SB);equal(await value('select count(*)::int from public.credit_ledger'),0)
  await runAs('authenticated',A,SA)
  for (let i=0;i<20;i++) await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['post-media',`${A}/object-${i}`])
  await rejects('insert into storage.objects(bucket_id,name) values($1,$2)',['post-media',`${A}/object-21`])
  await db.query("insert into public.posts(user_id,idea,platform,tone,caption,status) select $1,'Quota fixture','LinkedIn','Friendly','Test','draft' from generate_series(1,199)",[A])
  equal(await value('select count(*)::int from public.posts'),200)
  await rejects("insert into public.posts(user_id,idea,platform,tone,caption,status) values($1,'Over quota','LinkedIn','Friendly','Test','draft')",[A])
  await runAs('postgres')
  await db.exec("insert into storage.objects(bucket_id,name) select 'post-media','test-global/'||n from generate_series(1,60)n")
  await runAs('authenticated',B,SB)
  await rejects('insert into storage.objects(bucket_id,name) values($1,$2)',['post-media',`${B}/global-over-quota`])
  await runAs('postgres');await db.query('delete from auth.sessions where id=$1',[SA])
  await runAs('authenticated',A,SA)
  equal(await value('select public.has_active_session()'),false)
  equal(await value('select count(*)::int from public.posts'),0)
  equal(await value('select count(*)::int from storage.objects'),0)
  equal(await value('select public.consume_ai_quota()'),false)
  await rejects('select public.usage_summary()')
  await rejects("insert into public.posts(user_id,idea,platform,tone,caption,status) values($1,'Old JWT','LinkedIn','Friendly','Test','draft')",[A])
  await runAs('anon')
  await rejects('select public.has_active_session()')
  await rejects('select public.service_record_payment($1,$2,$3,$4,$5,$6)',['forged','plink_Test123',O,10000,'INR','pay_Test123'])
  await runAs('postgres')
  const dangerous = await db.query("select p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef")
  equal(dangerous.rows,[])
  console.log(`PASS: ${checks} local PostgreSQL checks; ownership, revocation, immutable approvals, publication gates/leases, OAuth replay, payment replay and paid-credit accounting. No network calls or live changes.`)
} finally { await db.close() }
